<?php

namespace TestAutomationCoreBundle\Repository;

use TestAutomationCoreBundle\Entity\BehatReport;
use TestAutomationCoreBundle\Entity\QueueTest;

/**
 * BehatReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BehatReportRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBehatReport(QueueTest $queueTest)
    {
        $resultSearch = self::findOneBy(['queueTestId' => $queueTest]);
        if ($resultSearch == null) {
            $behatReport = new BehatReport();
            $behatReport->setQueueTestId($queueTest);
            $this->getEntityManager()->merge($behatReport);
            $this->getEntityManager()->flush();
            return $behatReport;
        } else {
            return $resultSearch;
        }
    }

    /**@var QueueTest $queueTestObject */
    public function afterScenarioUpdate($queueTestObject, $isPass, $stepsText, $imagesDataArray,$passStep,$failStep)
    {
        if(!$isPass){
            $queueTestObject->setStatus(QueueTest::STATUS_FAIL);
            /**@var QueueTest $queueTestObject*/
            $queueTestObject = $this->getEntityManager()->merge($queueTestObject);
            $this->getEntityManager()->flush();

            $behatReportObject = new BehatReport();
            $behatReportObject->setQueueTestId($queueTestObject);
            $behatReportObject->setSteps($stepsText);
            $behatReportObject->setFailStep($failStep);
            $behatReportObject->setPassStep($passStep);
            $this->getEntityManager()->merge($behatReportObject);
            $this->getEntityManager()->flush();
            $imageRep = $this->getEntityManager()->getRepository('TestAutomationCoreBundle:ImageReport');
            foreach ($imagesDataArray as $image){
                $imageRep->createImage($image,$queueTestObject);
            }
        }else{
            $queueTestObject->setStatus(QueueTest::STATUS_PASS);
            /**@var QueueTest $queueTestObject*/
            $queueTestObject = $this->getEntityManager()->merge($queueTestObject);
            $this->getEntityManager()->flush();
        }

    }




}
