<?php

namespace TestAutomationCoreBundle\Repository;
use TestAutomationCoreBundle\Entity\ImageReport;
use TestAutomationCoreBundle\Entity\QueueTest;

/**
 * ImageReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageReportRepository extends \Doctrine\ORM\EntityRepository
{
    /**@var QueueTest $queueTestObject*/
    public function createImage($dataImage,$queueTestObject){
        $imageObject = new ImageReport();
        $imageObject->setQueueTestId($queueTestObject);
        $imageObject->setDataImage($dataImage);
        $imageObject = $this->getEntityManager()->merge($imageObject);
        $this->getEntityManager()->flush();
        $imageObject->upload();
        $this->getEntityManager()->merge($imageObject);
        $this->getEntityManager()->flush();
    }


}
