<?php

namespace TestAutomationCoreBundle\Repository;

use TestAutomationCoreBundle\Entity\Scenario;

/**
 * ScenarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScenarioRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $tagId
     * @return null|object|Scenario
     */
    public function getScenarioByTagId($tagId){
        $id = str_replace("ID=","",$tagId);
        $id = str_replace("@","",$id);
        $result = $this->findOneBy(["tagId"=>$id]);
        return $result;
    }
}
